#!/bin/bash

set -e

apt-get update -y
apt-get install -y git

GO_VERSION=`curl https://golang.org/VERSION\?m=text`
GO_VERSION=${GO_VERSION/go/}
GO_ARCH=`uname -m`

curl -LO https://golang.org/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
tar -C /usr/local -xzf go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
rm -rf go${GO_VERSION}.linux-${GO_ARCH}.tar.gz

echo '' >> /root/.bashrc
echo 'export GOPATH=/go' >> /root/.bashrc
echo 'export GOROOT=/usr/local/go' >> /root/.bashrc
echo 'export PATH=${PATH}:${GOROOT}/bin:${GOPATH}/bin' >> /root/.bashrc
source /root/.bashrc

# golang remote debug tool
go get github.com/go-delve/delve/cmd/dlv
