name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build latest
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dozer47528/devops-toolkits-docker:latest
      - name: Build golang
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.golang
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dozer47528/devops-toolkits-docker:golang
      - name: Build benchmark
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.benchmark
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dozer47528/devops-toolkits-docker:benchmark
      - name: Build database
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.database
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dozer47528/devops-toolkits-docker:database
      - name: Build jdk11
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.jdk11
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dozer47528/devops-toolkits-docker:jdk11
      - name: Build jdk8
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.jdk8
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dozer47528/devops-toolkits-docker:jdk8
      - name: Build websocket
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.websocket
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dozer47528/devops-toolkits-docker:websocket